# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Biology FYI
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This site hopes to provide usefull and entertaining information about UTA biology.
baseurl: "/biology"
url: ""

# Social media profiles - feel free to add more here
#twitter_username: jekyllrb
github_username:  dpneumo

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
permalink: pretty

repository: dpneumo/dpneumo.github.io
github: [metadata]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
